### ISSUE TITLE
Entity index XXX is not a valid client

### ISSUE THREAD

**Issue by akochanov** [Starblaster64/VSH-enhanced-stock-melees#7]
Hi, I installed a plugin on my VSH server and I have some problem. May be that it will help you solve these mistakes:
L 01/19/2016 - 17:32:08: [SM] Displaying call stack trace for plugin "hale_melees.smx":
L 01/19/2016 - 17:32:08: [SM]   [0]  Line 258, hale_melees.sp::OnTakeDamageAlive()
L 01/19/2016 - 17:32:17: [SM] Native "GetPlayerWeaponSlot" reported: Entity index 0 is not a valid client
L 01/19/2016 - 17:32:17: [SM] Displaying call stack trace for plugin "hale_melees.smx":
L 01/19/2016 - 17:32:17: [SM]   [0]  Line 258, hale_melees.sp::OnTakeDamageAlive()
L 01/19/2016 - 17:32:19: [SM] Native "GetPlayerWeaponSlot" reported: Entity index 115 is not a valid client
L 01/19/2016 - 17:32:19: [SM] Displaying call stack trace for plugin "hale_melees.smx":
L 01/19/2016 - 17:32:19: [SM]   [0]  Line 258, hale_melees.sp::OnTakeDamageAlive()

**Comment by Starblaster64** [comment]
Heh, honestly I didn't expect anyone to even find this. It was just something I came up with while I was bored. Because of that, I didn't extensively test it as much as I would have if it were part of the actual VSH plugin.
I'll take a look at what's wrong and see what I can do. No promises though, I'm a mildly lazy individual.

**Comment by Starblaster64** [comment]
Also, could you provide a little more context of the error?

**Comment by akochanov** [comment]
OK, I'll try to figure out the conditions under which it occurs

**Comment by Starblaster64** [comment]
Commit 51b5f5a on the `develop` branch should fix this issue, try the `develop` branch version of the plugin and tell me if the errors persist.

**Comment by akochanov** [comment]
L 01/21/2016 - 22:29:12: [SM] Displaying call stack trace for plugin "hale_melees.smx":
L 01/21/2016 - 22:29:12: [SM]   [0]  Line 256, hale_melees.sp::OnTakeDamageAlive()
L 01/21/2016 - 22:29:18: [SM] Native "IsPlayerAlive" reported: Invalid client index 0
L 01/21/2016 - 22:29:18: [SM] Displaying call stack trace for plugin "hale_melees.smx":
L 01/21/2016 - 22:29:18: [SM]   [0]  Line 256, hale_melees.sp::OnTakeDamageAlive()
L 01/21/2016 - 22:29:26: [SM] Native "IsPlayerAlive" reported: Invalid client index 0
L 01/21/2016 - 22:29:26: [SM] Displaying call stack trace for plugin "hale_melees.smx":
L 01/21/2016 - 22:29:26: [SM]   [0]  Line 256, hale_melees.sp::OnTakeDamageAlive()

**Comment by Starblaster64** [comment]
Any more information on when this was occurring? I have a hunch it might be related to Sentry Gun damage, but if you were experiencing this in some other scenario then that might not be it.

**Comment by Starblaster64** [comment]
Ok, just pushed another 'fix' (75401f5) to the `develop` branch. I'm pretty sure this one should solve all Invalid client issues. For some reason I never put in any IsValidClient checks into OTDA even though I took the Stock for it from VSH for that purpose in the first place.

**Comment by akochanov** [comment]
Hi, I tested the plugin for two days. I havent errors in the log file now. Thanks for fix.
