### ISSUE TITLE
Plugin encountered error 25: Call was aborted

### ISSUE THREAD

**Issue by akochanov** [Starblaster64/VSH-enhanced-stock-melees#8]
Hi, another mistake

> L 01/30/2016 - 16:11:20: SourceMod error session started
> L 01/30/2016 - 16:11:20: Info (map "koth_king") (file "errors_20160130.log")
> L 01/30/2016 - 16:11:20: [SM] Plugin encountered error 25: Call was aborted
> L 01/30/2016 - 16:11:20: [SM] Native "ThrowError" reported: Client 4 is not in game
> L 01/30/2016 - 16:11:20: [SM] Displaying call stack trace for plugin "hale_melees.smx":
> L 01/30/2016 - 16:11:20: [SM]   [0]  Line 43, C:\Servers\SRVGAME01\tf2(5)\tf\addons\sourcemod\scripting\include\morecolors.inc::CPrintToChat()
> L 01/30/2016 - 16:11:20: [SM]   [1]  Line 342, hale_melees.sp::Timer_TauntBonusEngineer()
> L 01/30/2016 - 16:13:28: Error log file session closed.

**Comment by Starblaster64** [comment]
That would be due to the TauntBonus timers firing after a player has triggered them, but then left the server (presumably). I'll just add checks to see if the player still still alive/valid/in-game before all the TauntBonus timers do the rest of their effects and that should fix it, hopefully.

**Comment by Starblaster64** [comment]
Just pushed commit aab1eca to the `develop` branch, it should fix the problem.

**Comment by akochanov** [comment]
I think you can close this request. Thank you alot for your help! Fixed!
